# Generated by Django 5.0.4 on 2025-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
