# Generated by Django 5.0.4 on 2025-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_currentbalance_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentbalance',
            name='expense_amount',
        ),
        migrations.RemoveField(
            model_name='currentbalance',
            name='income_amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='expense', max_length=10),
        ),
    ]
